// Date: 4/21/2013 7:10:34 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package hangcow.greatersecurity.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLaserEmitter extends ModelBase
{
	// fields
	ModelRenderer body;
	ModelRenderer eyeone;
	ModelRenderer eyetwo;
	ModelRenderer eyethree;
	ModelRenderer bodytop;
	ModelRenderer bodybot;
	ModelRenderer bodyleft;
	ModelRenderer bodyright;
	ModelRenderer laserone;
	ModelRenderer lasertwo;
	ModelRenderer laserthree;

	public ModelLaserEmitter()
	{
		textureWidth = 64;
		textureHeight = 32;

		body = new ModelRenderer(this, 0, 0);
		body.addBox(-2.5F, 0F, 0F, 5, 14, 3);
		body.setRotationPoint(0F, 8F, -8F);
		body.setTextureSize(64, 32);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		eyeone = new ModelRenderer(this, 0, 20);
		eyeone.addBox(-1.5F, -0.5F, 3F, 3, 3, 1);
		eyeone.setRotationPoint(0F, 9F, -8F);
		eyeone.setTextureSize(64, 32);
		eyeone.mirror = true;
		setRotation(eyeone, 0F, 0F, 0F);
		eyetwo = new ModelRenderer(this, 0, 20);
		eyetwo.addBox(-1.5F, 8.5F, 3F, 3, 3, 1);
		eyetwo.setRotationPoint(0F, 9F, -8F);
		eyetwo.setTextureSize(64, 32);
		eyetwo.mirror = true;
		setRotation(eyetwo, 0F, 0F, 0F);
		eyethree = new ModelRenderer(this, 0, 20);
		eyethree.addBox(-1.5F, 4F, 3F, 3, 3, 1);
		eyethree.setRotationPoint(0F, 9F, -8F);
		eyethree.setTextureSize(64, 32);
		eyethree.mirror = true;
		setRotation(eyethree, 0F, 0F, 0F);
		bodytop = new ModelRenderer(this, 18, 0);
		bodytop.addBox(-2F, 0F, 0F, 4, 2, 2);
		bodytop.setRotationPoint(0F, 22F, -8F);
		bodytop.setTextureSize(64, 32);
		bodytop.mirror = true;
		setRotation(bodytop, 0F, 0F, 0F);
		bodybot = new ModelRenderer(this, 18, 0);
		bodybot.addBox(-2F, -2F, 0F, 4, 2, 2);
		bodybot.setRotationPoint(0F, 8F, -8F);
		bodybot.setTextureSize(64, 32);
		bodybot.mirror = true;
		setRotation(bodybot, 0F, 0F, 0F);
		bodyleft = new ModelRenderer(this, 21, 6);
		bodyleft.addBox(2.5F, 1F, 0F, 1, 12, 2);
		bodyleft.setRotationPoint(0F, 8F, -8F);
		bodyleft.setTextureSize(64, 32);
		bodyleft.mirror = true;
		setRotation(bodyleft, 0F, 0F, 0F);
		bodyright = new ModelRenderer(this, 21, 6);
		bodyright.addBox(-3.5F, 1F, 0F, 1, 12, 2);
		bodyright.setRotationPoint(0F, 8F, -8F);
		bodyright.setTextureSize(64, 32);
		bodyright.mirror = true;
		setRotation(bodyright, 0F, 0F, 0F);
		laserone = new ModelRenderer(this, 28, 14);
		laserone.addBox(-1F, 4.5F, 0F, 2, 2, 16);
		laserone.setRotationPoint(0F, 9F, -8F);
		laserone.setTextureSize(64, 32);
		laserone.mirror = true;
		setRotation(laserone, 0F, 0F, 0F);
		lasertwo = new ModelRenderer(this, 28, 14);
		lasertwo.addBox(-1F, 0F, 0F, 2, 2, 16);
		lasertwo.setRotationPoint(0F, 9F, -8F);
		lasertwo.setTextureSize(64, 32);
		lasertwo.mirror = true;
		setRotation(lasertwo, 0F, 0F, 0F);
		laserthree = new ModelRenderer(this, 28, 14);
		laserthree.addBox(-1F, 9F, 0F, 2, 2, 16);
		laserthree.setRotationPoint(0F, 9F, -8F);
		laserthree.setTextureSize(64, 32);
		laserthree.mirror = true;
		setRotation(laserthree, 0F, 0F, 0F);
	}

	public void render(float f5)
	{
		body.render(f5);
		eyeone.render(f5);
		eyetwo.render(f5);
		eyethree.render(f5);
		bodytop.render(f5);
		bodytop.render(f5);
		bodyleft.render(f5);
		bodyright.render(f5);

	}

	public void renderLaser(float f5)
	{
		laserone.render(f5);
		lasertwo.render(f5);
		laserthree.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
